# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.1
  - 1
  - nightly
notifications:
  email: false

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'using Pkg; pkg"registry add General https://github.com/HolyLab/HolyLabRegistry.git"'
  - julia -e 'using Pkg; Pkg.build(); Pkg.test(;coverage=true)'

after_success:
# update the documentation
  - julia -e 'using Pkg; Pkg.add("Documenter")'
  - julia -e 'using RegisterMismatch; cd(dirname(dirname(pathof(RegisterMismatch)))); ENV["DOCUMENTER_DEBUG"] = "true"; include(joinpath("docs", "make.jl"))'
